
log:
  config_path:  "D:\\git\\fintech\\qstrader\\logging.yml"

out_path:       "D:\\git\\fintech\\qstrader\\out"

data_path:      "D:\\git\\fintech\\qstrader\\data"

stopword_file:  "D:\\git\\fintech\\qstrader\\data\\basic\\stopword.txt"

lock_timeout:   10

spider:
  bot_name:   "QSpiders"
  user_agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
  classes:
    - id:   0
      name: "Finance News Spider"
      seeds:
        - url:            "http://roll.hexun.com/roolNews_listRool.action?type=all&ids=100,101,103,125,105,124,162,194,108,122,121,119,107,116,114,115,182,120,169,170,177,180,118,190,200,155,130,117,153,106&page=%d&date=%s"
          name:           "hexun"
          full_max_page:  100
          incr_max_page:  10
          page_num:       30
          enable:         False
        - url:            "http://3g.163.com/touch/reconstruct/article/list/BA8EE5GMwangning/%d-%d.html"
          name:           "netease"
          full_max_page:  3
          incr_max_page:  1
          page_num:       100
          enable :        False
        - url:            "https://xueqiu.com/v4/statuses/public_timeline_by_category.json?category=-1&since_id=-1&count=%d&max_id=%s"
          name:           "xueqiu"
          full_max_page:  100
          incr_max_page:  10
          page_num:       20
          enable :        False
        - url:            ["http://finance.eastmoney.com/news/cywjh_%s.html", "http://finance.eastmoney.com/news/cgnjj_%s.html", "http://finance.eastmoney.com/news/cgjjj_%s.html", "http://finance.eastmoney.com/news/czqyw_%s.html", "http://finance.eastmoney.com/news/cgsxw_%s.html"]
          name:           "eastmoney"
          full_max_page:  25
          incr_max_page:  3
          page_num:       20
          enable :        False
        - url:            "http://feed.mix.sina.com.cn/api/roll/get?pageid=155&lid=1686&num=%s&page=%s&callback=feedCardJsonpCallback&_=%s"
          name:           "sina"
          full_max_page:  100
          incr_max_page:  10
          page_num:       20
          enable :        False
        - url:            "http://roll.finance.qq.com/interface/roll.php?cata=&site=finance&date=&page=%s&mode=1&of=json&%s"
          name:           "qq"
          full_max_page:  10
          incr_max_page:  2
          page_num:       50
          enable :        True
      title_filters:    ["上海金交所", "十只个股"]
      content_filters:  ["和讯网今天刊登了", "郑重声明：东方财富网发布此信息目的"]
      out_folder:       "spider"
      out_lock_file:    "fin_news.lock"
      out_db_file:      "fin_news.db"
      out_news_file:    "fin_news.txt"
      full_max_page:    100
      incr_max_page:    10

corpus:
  classes:
    - id:             0
      name:           "Finance News Corpus"
      dictionary:
        no_below:     2
        no_above:     0.5
        keep_n:       100000
      in_news_file:   "spider/fin_news.txt"
      days_ago:       2
      out_folder:     "corpus"
      out_lock_file:  "fin_news.lock"
      out_id_file:    "fin_news.ids"
      out_seg_file:   "fin_news.seg"
      out_pos_file:   "fin_news.pos"
      out_dic_file:   "fin_news.dic"
      out_d2b_file:   "fin_news.d2b"
      out_tfidf_file: "fin_news.tfidf"

sentiment:
  classes:
    - id:             0
      name:           "Finance News Sentiment"
      topic:
        num_topics:     200
        num_words:      100
        eval_every:     5
        chunksize:      50
        workers:        4
        passes:         10
      cluster:
        num_clusters_factor:   3
        d2c_file:       "fin_news.d2c"
        d2c_fig_file:   "fin_news.d2c.png"
        d2c_top_ratio:  0.02
        t2c_file:       "fin_news.t2c"
        t2c_fig_file:   "fin_news.t2c.png"
      keyword:
        num_keywords:   30
      nmf:
        num_words:      1000
        num_comps:      3
      out_folder:       "sentiment"
      out_lock_file:    "fin_news.lock"
      out_id_file:      "fin_news.ids"      
      out_tpc_file:     "fin_news.tpc"   
      out_d2v_file:     "fin_news.d2v"

data:
  tushare:
    basic_stock_file: "basic/stock_%s.csv"